version: '3.7'

services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        user: vscode
        command: sleep infinity
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: mypass143
            MYSQL_ROOT_PASSWORD: yourpass143
        ports:
            - '3306:3306'
        volumes:
            - data-volume:/var/lib/mysql
volumes:
    data-volume: