version: '3.7'

services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        user: vscode
        command: sleep infinity
    mysql:
        image: mysql:latest
        volumes:
            - data-volume:/var/lib/mysql
volumes:
    data-volume: